swagger: "2.0"
info:
  description: "A aplicação é um simples repositório para gerenciar ferramentas com seus respectivos nomes, links, descrições e tags. For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "VUTTR (Very Useful Tools to Remember)"
host: "localhost:3000"
basePath: "/"
tags:
- name: "tools"
  description: "Métodos relacionados à Ferramentas (tools)"
- name: "user"
  description: "Métodos relacionados à Usuários"
schemes:
- "http"
- "https"
paths:
  /tools:
    get:
      tags:
      - "tools"
      summary: "Lista todas as ferramentas cadastradas"
      operationId: "listTool"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Operação realizada com sucesso"
        500:
          description: "Internal Server Error"
    post:
      tags:
      - "tools"
      summary: "Adiciona uma nova ferramenta"
      description: ""
      operationId: "addTool"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Ferramenta que será criada"
        required: true
        schema:
          $ref: "#/definitions/ToolSchema"
      responses:
        500:
          description: "Internal Server Error"
  /tools?tag={tag}:
    get:
      tags:
      - "tools"
      summary: "Lista ferramentas que contenham a tag selecionada"
      description: ""
      operationId: "getToolByTag"
      produces:
      - "application/json"
      parameters:
      - name: "tag"
        in: "path"
        description: "Tag a ser buscada"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Pet"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
      security:
      - api_key: []
  /tools/{id}:
    patch:
      tags:
      - "tools"
      summary: "Atualizar os dados da ferramenta selecionada"
      description: ""
      operationId: "updatePetWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "petId"
        in: "path"
        description: "ID of pet that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "name"
        in: "formData"
        description: "Updated name of the pet"
        required: false
        type: "string"
      - name: "status"
        in: "formData"
        description: "Updated status of the pet"
        required: false
        type: "string"
      responses:
        405:
          description: "Invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    delete:
      tags:
      - "tools"
      summary: "Remove uma ferramenta"
      description: ""
      operationId: "deletePet"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "petId"
        in: "path"
        description: "Pet id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  ToolSchema:
    type: "object"
    properties:
      title:
        type: "string"
        required: true
      link:
        type: "string"
        required: true
      description:
        type: "string"
        required: true
      tags:
         type: "array"