swagger: "2.0"
info:
  description: "A aplicação é um simples repositório para gerenciar ferramentas com seus respectivos nomes, links, descrições e tags. Neste exemplo você pode usar o User `AuthUser`, com Senha `authuser` para testar."
  version: "1.0.0"
  title: "VUTTR (Very Useful Tools to Remember)"
host: "bossaboxbackend.herokuapp.com"
basePath: "/"
tags:
- name: "auth"
  description: "Autenticação do Usuário"
- name: "tools"
  description: "Métodos relacionados à Ferramentas (tools)"
schemes:
- "http"
- "https"
paths:
  /auth:
    post:
      tags:
      - "auth"
      summary: "Autentica um Usuário e lhe concede um Token"
      description: ""
      operationId: "authUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/UserSchema"
      responses:
        200:
          description: "Operação bem sucedida"
        401:
          description: "Error: Unauthorized"
  /tools:
    get:
      tags:
      - "tools"
      summary: "Lista todas as ferramentas cadastradas"
      operationId: "listTool"
      produces:
      - "application/json"
      responses:
        200:
          description: "Operação bem sucedida"
        500:
          description: "Internal Server Error"
    post:
      tags:
      - "tools"
      summary: "Adiciona uma nova ferramenta"
      description: ""
      operationId: "addTool"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/ToolSchema"
      responses:
        201:
          description: "Operação bem sucedida"
          schema:
            $ref: "#/definitions/ToolSchema"
        500:
          description: "Internal Server Error"
      security:
      - api_key: []
  /tools?tag={tag}:
    get:
      tags:
      - "tools"
      summary: "Lista as ferramentas que contenham a tag solicitada"
      description: ""
      operationId: "toolsByTag"
      produces:
      - "application/json"
      parameters:
      - name: "tag"
        in: "path"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "Operação bem sucedida"
          schema:
            $ref: "#/definitions/ToolSchema"
        500:
          description: "Internal Server Error"
  /tools/{id}:
    patch:
      tags:
      - "tools"
      summary: "Atualiza uma ferramenta"
      description: ""
      operationId: "updateTool"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: ""
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Objeto contendo os dados atualizados"
        required: true
        schema:
          $ref: "#/definitions/ToolSchema"
      responses:
        201:
          description: "Operação bem sucedida"
          schema:
            $ref: "#/definitions/ToolSchema"
        500:
          description: "Internal Server Error"
      security:
      - api_key: []
    delete:
      tags:
      - "tools"
      summary: "Remove uma ferramenta a partir do Id"
      description: ""
      operationId: "deleteTool"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: ""
        required: true
        type: "string"
      responses:
        204:
          description: "Operação bem sucedida"
        500:
          description: "Internal Server Error"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-access-token"
    in: "header"
definitions:
  UserSchema:
    type: "object"
    properties:
      username:
        type: "string"
        required: true
      password:
        type: "string"
        required: true
  ToolSchema:
    type: "object"
    properties:
      title:
        type: "string"
        required: true
      link:
        type: "string"
        required: true
      description:
        type: "string"
        required: true
      tags:
         type: "array"
         items:
          type: "string"
